heat_template_version: 2014-10-16

description: Deploys an OpenStack instance for Minecraft

parameters:
  #Minecraft Customization
  minecraft_gamemode:
    type: number
    label: Game Mode
    description: Game Mode for Minecraft.  0 - Survival, 1 - Creative, 2 - Adventure, 3 - Spectator
    default: 1
    constraints:
    - allowed_values:
      - 0
      - 1
      - 2
      - 3
  minecraft_difficulty:
    type: number
    label: Difficulty
    description: Difficulty level for Minecraft.  0 - Peaceful, 1 - Easy, 2 - Normal, 3 - Hard
    default: 2
    constraints:
    - allowed_values:
      - 0
      - 1
      - 2
      - 3
  minecraft_monsters:
    type: boolean
    label: Spawn Monsters
    description: Enable or disable spawning of hostile mobs
    default: false
  minecraft_hardcore:
    type: boolean
    label: Hardcore Mode
    description: Enable or disable Hardcore mode.  In Hardcore mode, users will be banned from the server upon death
    default: false
  minecraft_animals:
    type: boolean
    label: Spawn Animals
    description: Enable or disable spawning of passive mobs
    default: true
  minecraft_npcs:
    type: boolean
    label: Spawn NPCs
    description: Enable or disable spawning of villagers
    default: true
  minecraft_motd:
    type: string
    label: Message Of The Day
    description: Message to be displayed in the server list
    default: A Minecraft Server
    constraints:
    - length: { min: 0, max: 59 }
  minecraft_max_players:
    type: number
    label: Maximum Players
    description: Maximum number of players able to connect at any given time
    default: 20
    constraints:
    - range: {min: 1, max: 999}

  minecraft_online:
    type: boolean
    label: Online
    default: true
    description: Online mode requires clients to have a valid Minecraft account.

  public_net_id:
    type: string
    label: Public Network UUID
    description: UUID of public network from which floating IP addresses will be allocated

  instance_flavor:
    type: string
    label: Flavor
    default: m1.medium
    description: Flavor to use for Minecraft
    constraints:
    - allowed_values:
      - m1.small
      - m1.medium
      - m1.large
      - m1.xlarge

  instance_image:
    type: string
    label: Image
    default: ubuntu_1404_server_cloudimg_amd64
    description: Image to be used for all servers in this stack

resources:
  #SSH Key
  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  #Networking
  tenant_network:
    type: OS::Neutron::Net
    properties:
      name: minecraft
      shared: false

  tenant_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: tenant_network }
      ip_version: 4
      dns_nameservers: [8.8.8.8]
      cidr: 10.0.0.0/24
      gateway_ip: 10.0.0.1

  router:
    type: OS::Neutron::Router
    properties:
      name: minecraftRouter
      external_gateway_info:
        network: { get_param: public_net_id }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: tenant_subnet }

  minecraft_server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: tenant_network }
      security_groups: [{ get_resource: minecraft_security_group }]

  minecraft_server_floating_ip:
    type: OS::Neutron::FloatingIP
    depends_on: router_interface
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: minecraft_server_port }

  minecraft_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description:
      name: minecraft-security-group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 25565
          port_range_max: 25565
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp

  #Master Server
  minecraft_server:
    type: OS::Nova::Server
    properties:
      name: minecraft
      image: { get_param: instance_image }
      flavor: { get_param: instance_flavor }
      key_name: { get_resource: ssh_key }
      networks:
        - port: { get_resource: minecraft_server_port }
      user_data_format: RAW
      user_data:
        str_replace:
           template: |
              #!/bin/bash
              add-apt-repository -y ppa:ansible/ansible
              apt-get update
              apt-get -y upgrade
              apt-get install -y unzip git wget ansible python2.7 software-properties-common
              mkdir -p /etc/ansible/roles
              git clone https://github.com/hhoover/minecraft-role.git /etc/ansible/roles
              ansible-playbook /etc/ansible/roles/playbook.yaml --extra-vars "minecraft_gamemode=%minecraft_gamemode% minecraft_difficulty=%minecraft_difficulty% minecraft_monsters=%minecraft_monsters% minecraft_hardcore=%minecraft_hardcore% minecraft_animals=%minecraft_animals% minecraft_npcs=%minecraft_npcs% minecraft_motd=%minecraft_motd% minecraft_max_players=%minecraft_max_players% minecraft_online=%minecraft_online%"
           params:
             "%minecraft_gamemode%": { get_param: minecraft_gamemode }
             "%minecraft_difficulty%": { get_param: minecraft_difficulty }
             "%minecraft_monsters%": { get_param: minecraft_monsters }
             "%minecraft_hardcore%": { get_param: minecraft_hardcore }
             "%minecraft_animals%": { get_param: minecraft_animals }
             "%minecraft_npcs%": { get_param: minecraft_npcs }
             "%minecraft_motd%": { get_param: minecraft_motd }
             "%minecraft_max_players%": { get_param: minecraft_max_players }
             "%minecraft_online%": { get_param: minecraft_online }

outputs:
  minecraft_ip:
    description: Server Public IP
    value: { get_attr: [ minecraft_server_floating_ip, floating_ip_address ] }
  ssh_private_key:
    description: SSH Private Key
    value: { get_attr: [ssh_key, private_key] }
